[package]
name = "miri-the-world"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
crates_io_api = "0.8.0"
env_logger = "0.9.0"
log = "0.4.16"
regex = "1.5.5"
tempfile = "3.3.0"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }
ureq = "2.4.0"
lazy_static = "1.4.0"
flate2 = "1.0.22"
tar = "0.4.38"
ansi-to-html = { git = "https://github.com/Aloso/to-html", features = ["once_cell"] }

[profile.release]
panic = "abort"
debug = 1
